
#数据源配置
spring:
  application:
    name: enterprise-service

  datasource:
    url: jdbc:mysql://rm-2ze1oiwuqgur01f4q.mysql.rds.aliyuncs.com/enterprise
    username: zhaobangshou
    password: 123qweQWE
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: enterprise-pool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1

  redis:
        #数据库索引
        database: 0
        host: 127.0.0.1
        port: 6379
        password: admin123
        jedis:
          pool:
            #最大连接数
            max-active: 8
            #最大阻塞等待时间(负数表示没限制)
            max-wait: -1
            #最大空闲
            max-idle: 8
            #最小空闲
            min-idle: 0
        #连接超时时间
        timeout: 10000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 10001
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  path: /home/logs/


file:
  path: /home/data/